image: node:latest

stages:
  - CI
  - Staging
  - Prod
build:
  stage: CI
  script:
    - yarn install
    - yarn test:unit

deploy-full-stage:
  stage: Staging
  script:
    - yarn install
    - yarn deploy:full:stage --token $FIREBASE_TOKEN

deploy-lite-stage:
  stage: Staging
  script:
    - yarn install
    - yarn deploy:lite:stage --token $FIREBASE_TOKEN

deploy-full-prod:
  stage: Prod
  script:
    - yarn install
    - yarn deploy:full:prod --token $FIREBASE_TOKEN
  when: manual
  only:
    - master

deploy-lite-prod:
  stage: Prod
  script:
    - yarn install
    - yarn deploy:lite:prod --token $FIREBASE_TOKEN
  when: manual
  only:
    - master
